### ISSUE TITLE
dingding@人告警bug

### ISSUE THREAD

**Issue by guolin302** [xthz/ding#1]
将dingding@人的手机号设置为变量就提示 "parameter error, \"at\" parameter must be in \"*\" or mobile phone number format"
例如at := `"` + "13188888888" + `"` + `,` + `"` + "13188888888" + `"`
SendMessageText(content, dingPhoneList)

**Comment by xthz** [comment]
使用 at 时, 正确的格式是这样的:

```go
err := d.SendMessageText("xxxx", "13188888888", "13188888888")
```

**Comment by xthz** [comment]
如果你想将手机号作为变量使用, 正确的格式是这样的:

```go
at := []string{"13188888888", "13188888888"}
err := d.SendMessageText("xxxx", at...)
```
